version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./backend/
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
  redis:
    image: "redis:alpine"
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

